#!/bin/bash

BASEDIR="$(dirname "$(readlink -f "$0")")"

case  "$1" in 
"view") python ${BASEDIR}/machineviewer.py;;

"play") python ${BASEDIR}/BoardLauncher.py;;

"arena") python ${BASEDIR}/chess_arena.py --go;;

"tournament") python ${BASEDIR}/launch_tournament.py;;

"longtournament") python ${BASEDIR}/launch_tournament.py -t;;

"make") cd ${BASEDIR}/engine && ./make.sh;;

"memusage") cd ${BASEDIR}/ && python makegraphic.py show;;

"engine") cd ${BASEDIR}/ && ./engine/e-vchess;;

*) 
echo ""
echo " Invalid Option."
echo "";;
esac
