#!/bin/bash

BASEDIR="$(dirname "$(readlink -f "$0")")"

case  "$1" in 
"view") python ${BASEDIR}/machineviewer.py;;

"play") python ${BASEDIR}/BoardLauncher.py;;

"arena") python ${BASEDIR}/chess_arena.py --go;;

"tournament") python ${BASEDIR}/launch_tournament.py;;

"make") cd ${BASEDIR}/engine && sh make.sh;;

*) 
echo ""
echo " Invalid Option."
echo "";;
esac
