#!/bin/bash

BASEDIR="$(dirname "$(readlink -f "$0")")"

case  "$1" in 
"view") python ${BASEDIR}/machineviewer.py;;

"play") python ${BASEDIR}/BoardLauncher.py;;

"arena") python ${BASEDIR}/chess_arena.py --go;;

"noxarena") python ${BASEDIR}/chess_arena.py --nogui;;

"tournament") python ${BASEDIR}/launch_tournament.py;;

"longtournament") if [ -z ${2} ];
		  then wN=1;
		  else wN=$2;
		  fi
		  for i in `seq 1 ${wN}`;
		  do
		      echo -ne "\033]0; Long Tournament ${i}/${wN}\007" 
		      python ${BASEDIR}/launch_tournament.py -t
		  done;;

"list") ls ${BASEDIR}/machines/halloffame;;

"make") python ${BASEDIR}/generateParameters.py && cd ${BASEDIR}/engine && ./make.sh;;

"memusage") cd ${BASEDIR}/ && python makegraphic.py show;;

"engine") cd ${BASEDIR}/engine && ./lampreia $2 $3 $4 $5;;

"position") cd ${BASEDIR}/ && python moveTrainer.py $2 $3 $4 $5;;

"populate") cd ${BASEDIR}/ && python population.py populate 64;;
*) 
echo ""
echo " Invalid Option."
echo "";;
esac
